general {
    lock_cmd = pidof hyprlock || hyprlock       
    before_sleep_cmd = loginctl lock-session    
    after_sleep_cmd = hyprctl dispatch dpms on  
    ignore_dbus_inhibit = false
}

# 1. DIM SCREEN (2.5 min)
# Saves power and protects OLED/IPS panels.
listener {
    timeout = 150                                
    on-timeout = brightnessctl -s -d amdgpu_bl1 set 10% 
    on-resume = brightnessctl -r -d amdgpu_bl1           
}

# 2. TURN OFF KEYBOARD LIGHTS (2.5 min)
# Specific to your ThinkPad's 'tpacpi::kbd_backlight'
listener {
    timeout = 150                                
    on-timeout = brightnessctl -sd tpacpi::kbd_backlight set 0
    on-resume = brightnessctl -rd tpacpi::kbd_backlight
}

# 3. LOCK SCREEN (5 min)
listener {
    timeout = 300                                 
    on-timeout = loginctl lock-session            
}

# 4. DPMS OFF - SCREEN POWER DOWN (5.5 min)
listener {
    timeout = 330                                 
    on-timeout = hyprctl dispatch dpms off        
    on-resume = hyprctl dispatch dpms on          
}

# 5. SUSPEND (30 min)
listener {
    timeout = 1800                                
    on-timeout = systemctl suspend                
}
