listen_addresses = ['127.0.0.1:5300','[::1]:5300']

server_names = ['cloudflare','cloudflare-ipv6', 'google','google-ipv6']


max_clients = 250


# Use servers reachable over IPv4
ipv4_servers = true

# Use servers reachable over IPv6 -- Do not enable if you don't have IPv6 connectivity
ipv6_servers = false

# Use servers implementing the DNSCrypt protocol
dnscrypt_servers = true

# Use servers implementing the DNS-over-HTTPS protocol
doh_servers = true

# Use servers implementing the Oblivious DoH protocol
odoh_servers = false


## Require servers defined by remote sources to satisfy specific properties

# Server must support DNS security extensions (DNSSEC)
require_dnssec = false

# Server must not log user queries (declarative)
require_nolog = true

# Server must not enforce its own blocklist (for parental control, ads blocking...)
require_nofilter = true

# Server names to avoid even if they match all criteria
disabled_server_names = []



force_tcp = false


http3 = false

http3_probe = false


timeout = 5000



keepalive = 30



log_file = '/var/log/dnscrypt-proxy/dnscrypt-proxy.log'


use_syslog = true



# Maximum log files size in MB - Set to 0 for unlimited.
log_files_max_size = 10

# How long to keep backup files, in days
log_files_max_age = 7

# Maximum log files backups to keep (or 0 to keep all backups)
log_files_max_backups = 1


cert_refresh_delay = 240


bootstrap_resolvers = ['9.9.9.11:53', '8.8.8.8:53']


ignore_system_dns = true


netprobe_timeout = 60


netprobe_address = '9.9.9.9:53'



block_ipv6 = false


block_unqualified = true


block_undelegated = true


reject_ttl = 10



forwarding_rules = '/etc/dnscrypt-proxy/forwarding-rules.txt'


cache = true


## Cache size

cache_size = 4096


## Minimum TTL for cached entries

cache_min_ttl = 2400


## Maximum TTL for cached entries

cache_max_ttl = 86400


## Minimum TTL for negatively cached entries

cache_neg_min_ttl = 60


## Maximum TTL for negatively cached entries

cache_neg_max_ttl = 600



[captive_portals]

[local_doh]


[query_log]
format = 'tsv'



[nx_log]

format = 'tsv'



[blocked_names]
  blocked_names_file = '/etc/dnscrypt-proxy/hagezi.txt'


[blocked_ips]


[allowed_names]

[allowed_ips]


[schedules]

[sources]


[sources.public-resolvers]
urls = [
  'https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md',
  'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md',
]
cache_file = '/var/cache/dnscrypt-proxy/public-resolvers.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
refresh_delay = 73
prefix = ''

### Anonymized DNS relays

[sources.relays]
urls = [
  'https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/relays.md',
  'https://download.dnscrypt.info/resolvers-list/v3/relays.md',
]
cache_file = '/var/cache/dnscrypt-proxy/relays.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
refresh_delay = 73
prefix = ''



[broken_implementations]

fragments_blocked = [
  'cisco',
  'cisco-ipv6',
  'cisco-familyshield',
  'cisco-familyshield-ipv6',
  'cisco-sandbox',
  'cleanbrowsing-adult',
  'cleanbrowsing-adult-ipv6',
  'cleanbrowsing-family',
  'cleanbrowsing-family-ipv6',
  'cleanbrowsing-security',
  'cleanbrowsing-security-ipv6',
]



[doh_client_x509_auth]


[anonymized_dns]


skip_incompatible = false



[dns64]

[ip_encryption]

algorithm = "none"


key = ""



[monitoring_ui]

enabled = false

listen_address = "127.0.0.1:8080"

username = "admin"
password = "changeme"

tls_certificate = ""
tls_key = ""

enable_query_log = true

privacy_level = 1


[static]
